name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Show Folder Structure (Debugging)
        run: ls -R

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"

      - name: Install Backend Dependencies
        run: |
          cd backend   
          npm install

      - name: Install Frontend Dependencies
        run: |
          cd frontend  
          npm install

      - name: Build Frontend
        run: |
          cd frontend
          npm run build

      - name: Move Frontend Build to Backend (If Serving from Backend)
        run: mv frontend/dist backend/dist

      - name: Run Linter
        run: |
          cd backend
          npm run lint

      - name: Deploy to Render (Optional)
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
